### ISSUE TITLE
Suggested additional locations for "Add Volunteer"

### ISSUE THREAD

**Issue by SelinaTaylor** [trichards57/dips-extender#1]
The add volunteer link appears to be working well and isnt affecting any other functionality as far as I can determine :-)

Is it possible to add it to the following locations?

a) In the pre-allocate members to event tab under the list of volunteers signed up (i.e. where I used to do most of my adding after checking whether they are already signed up).

b) Def less important than a) but, given the pre-book volunteers to this event? button has never let you pre book volunteers, an actually book vols to event button might be a useful feature! ;-)

Thank-you :-)

**Comment by trichards57** [comment]
Okay, I'm going to break this up into ~~two~~ a few  tasks.

**Comment by trichards57** [comment]
Closed, replaced by #2, #4 and #5
